version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pgtransfer-test-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./sample-data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql:ro
    networks:
      - pgtransfer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgtransfer-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgtransfer.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pgtransfer-network
    depends_on:
      postgres:
        condition: service_healthy

  # Optional: SSH server for testing SSH tunnel functionality
  ssh-server:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: pgtransfer-ssh-server
    restart: unless-stopped
    environment:
      SSH_USERS: "sshuser:1000:1000:sshpass"
    ports:
      - "2222:22"
    networks:
      - pgtransfer-network
    command: >
      sh -c "
        echo 'AllowTcpForwarding yes' >> /etc/ssh/sshd_config &&
        echo 'GatewayPorts yes' >> /etc/ssh/sshd_config &&
        echo 'PermitTunnel yes' >> /etc/ssh/sshd_config &&
        /usr/sbin/sshd -D
      "

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  ssh_config:
    driver: local

networks:
  pgtransfer-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16